apiVersion: apps/v1
kind: Deployment
metadata:
  name: dennis2
  labels:
    app: dennis2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dennis2
  template:
    metadata:
      labels:
        app: dennis2
    spec:
      containers:
        - name: dennis2
          image: nginx
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: my-efs-volume
              mountPath: '/test'
      volumes:
        - name: my-efs-volume
          persistentVolumeClaim:
            claimName: my-efs-pvc
