apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap # what is ap?
  fileSystemId: fs-0eeb57a7aa9de13d6 #  EFS File System ID
  region: us-east-1
  directoryPerms: '777' # what is this?
