apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: pg-service
spec:
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 5432 # has to match container port
  clusterIP: None
  selector:
    app: postgres
