apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0fff5ab9729a6795c #EFS File System ID
