apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap # what is ap?
  fileSystemId: fs-0fff5ab9729a6795c #  EFS File System ID
  region: us-east-1
  directoryPerms: '777' # what is this?
