apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0eeb57a7aa9de13d6 #EFS File System ID
