apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432 # PostgreSQL default port
          env:
            # - name: POSTGRES_DB
            #   value: <your-database-name>
            # - name: POSTGRES_USER
            #   value: <your-username>
            - name: POSTGRES_PASSWORD
              value: testPass # should change
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
