apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: postgres-sc
  resources:
    requests:
      storage: 5Gi # Must be speficied, but is ignored since FS is elastic
